import { ProductType } from "./../types/product.type";
import Images from "../static";
const dataProduct: ProductType[] = [
  {
    id: 1,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay01,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 2,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay02,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 3,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay10,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 4,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay09,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 5,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay08,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 6,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay05,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 7,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay06,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
  {
    id: 8,
    name: "Giày Nike Air Force 1 Low Shadow Sunset Pulse (W)",
    href: "#",
    imageSrc: Images.giay07,
    imageAlt: "Front of men's Basic Tee in black.",
    price: "$35",
    color: "Black",
    off: "25%",
  },
];
export default dataProduct;
